BLOG/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
#from django.conf import settings
#from django.conf.urls.static import static

urlpatterns =[
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('members/', include('django.contrib.auth.urls')),
    path('members/', include('members.urls')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

members/urls.py
from django.urls import reverse, path
from django.contrib.auth import views as auth_views
from .views import RegisterView, EditProfileForm, PassChangeView
from .views import PassChangeView
from django.contrib.auth import views as auth_views
from django.http import HttpResponse
from. import views


app_name = 'members'

urlpatterns =[
    path('register/', RegisterView.as_view(), name='register'),
    path('edit_profile', EditProfileForm.as_view(), name='edit_profile'),
    # path('password/', auth_views.PasswordChangeView.as_view(template_name='registration/change-password.html')),
    path('password/', PassChangeView.as_view(template_name='registration/change-password.html')),
    path('success', views.success, name="success"),

    #path('test_password_reset/', debug_view, name='password_reset'),
   
]

templates/addPost.html
{% if user.is_authenticated %}
    <h1>Add Post</h1>

    <div class="form-group">
        <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.media}}
        {{form.as_p}}
        <button class=" =btn btn-secondary">Post</button>
        </form>
    </div>
    <script>
        var name = "{{user.username}}";
        document.getElementById("user").value = name;
    </script>
{% else %}
    <small>You are not allowed to perform this action</small>
{% endif %}

   

templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="Untree.co">
    <link rel="shortcut icon" href="{% static 'favicon.png' %}">

    <meta name="description" content="" />
    <meta name="keywords" content="bootstrap, bootstrap5" />

    <link rel="preconnect" href="{% static 'https://fonts.googleapis.com' %}">
    <link rel="preconnect" href="{% static 'https://fonts.gstatic.com' %}" crossorigin>
    <link href="{% static 'https://fonts.googleapis.com/css2?family=Work+Sans:wght@400;600;700&display=swap' %}" rel="stylesheet">


    <link rel="stylesheet" href="{% static 'fonts/icomoon/style.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/flaticon/font/flaticon.css' %}">

    <link rel="stylesheet" href="{% static 'https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css' %}">

    <link rel="stylesheet" href="{% static 'css/tiny-slider.css' %}">
    <link rel="stylesheet" href="{% static 'css/aos.css' %}">
    <link rel="stylesheet" href="{% static 'css/glightbox.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <link rel="stylesheet" href="{% static 'css/flatpickr.min.css' %}">


    <title>Blogy &mdash; Free Bootstrap 5 Website Template by Untree.co</title>
</head>
<body>
    
        <div class="site-mobile-menu site-navbar-target">
            <div class="site-mobile-menu-header">
                <div class="site-mobile-menu-close">
                    <span class="icofont-close js-menu-toggle"></span>
                </div>
            </div>
            <div class="site-mobile-menu-body"></div>
        </div>

        <nav class="site-nav">
            <div class="container">
                <div class="menu-bg-wrap">
                    <div class="site-navigation">
                        <div class="row g-0 align-items-center">
                            <div class="col-2">
                                <a href="{% static 'index.html' %}" class="logo m-0 float-start">Blogy<span class="text-primary">.</span></a>
                            </div>
                            <div class="col-8 text-center">
                                <form action="#" class="search-form d-inline-block d-lg-none">
                                    <input type="text" class="form-control" placeholder="Search...">
                                    <span class="bi-search"></span>
                                </form>

                                <ul class="js-clone-nav d-none d-lg-inline-block text-start site-menu mx-auto">
                                    <li class="active"><a href="{% url 'index' %}">Home</a></li>
                                    <li class="has-children">
                                        <a href="{% static 'category.html' %}">Pages</a>
                                        <ul class="dropdown">
                                            <li><a href="{% static 'search-result.html' %}">Search Result</a></li>
                                            <li><a href="{% static 'blog.html' %}">Blog</a></li>
                                            <li><a href="{% static 'single.html' %}">Blog Single</a></li>
                                            <li><a href="{% static 'category.html' %}">Category</a></li>
                                            <li><a href="{% static 'about.html' %}">About</a></li>
                                            <li><a href="{% static 'contact.html' %}">Contact Us</a></li>
                                            <li><a href="#">Menu One</a></li>
                                            <li><a href="#">Menu Two</a></li>
                                            <li class="has-children">
                                                <a href="#">Dropdown</a>
                                                <ul class="dropdown">
                                                    <li><a href="#">Sub Menu One</a></li>
                                                    <li><a href="#">Sub Menu Two</a></li>
                                                    <li><a href="#">Sub Menu Three</a></li>
                                                </ul>
                                            </li>
                                        </ul>
                                    </li>
                                    {% if user.is_authenticated %}
                                        <li><a href="{% url 'logout' %}">Logout</a></li>
                                        <li><a href="{% url 'addPost' %}">Add Post</a></li>
                                    {% else %}
                                        <li><a href="{% url 'members:register' %}">SignUp</a></li>
                                        <li><a href="{% url 'login' %}">Login</a></li>
                                    {% endif %}
                                </ul>
                            </div>
                            <div class="col-2 text-end">
                                <a href="#" class="burger ms-auto float-end site-menu-toggle js-menu-toggle d-inline-block d-lg-none light">
                                    <span></span>
                                </a>
                                <form action="#" class="search-form d-none d-lg-inline-block">
                                    <input type="text" class="form-control" placeholder="Search...">
                                    <span class="bi-search"></span>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </nav>

        <div class="container">
            <div class="row">
                <div class="col-lg-4 ps-lg-5">
                
                </div> <!-- /.col-lg-4 -->
            </div> <!-- /.row -->
        </div> <!-- /.container -->

        <div class="container">
            {% block content %}

            {% endblock %}
        </div> 

        <footer class="site-footer">
            <div class="container">
                <div class="row">
                    <div class="col-lg-4">
                        <div class="widget">
                            <h3 class="mb-4">About</h3>
                            <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
                        </div> <!-- /.widget -->
                        <div class="widget">
                            <h3>Social</h3>
                            <ul class="list-unstyled social">
                                <li><a href="#"><span class="icon-instagram"></span></a></li>
                                <li><a href="#"><span class="icon-twitter"></span></a></li>
                                <li><a href="#"><span class="icon-facebook"></span></a></li>
                                <li><a href="#"><span class="icon-linkedin"></span></a></li>
                                <li><a href="#"><span class="icon-pinterest"></span></a></li>
                                <li><a href="#"><span class="icon-dribbble"></span></a></li>
                            </ul>
                        </div> <!-- /.widget -->
                    </div> <!-- /.col-lg-4 -->
                    
                    <div class="col-lg-4 ps-lg-5">
                        <div class="widget">
                            <h3 class="mb-4">Company</h3>
                            <ul class="list-unstyled float-start links">
                                <li><a href="#">About us</a></li>
                                <li><a href="#">Services</a></li>
                                <li><a href="#">Vision</a></li>
                                <li><a href="#">Mission</a></li>
                                <li><a href="#">Terms</a></li>
                                <li><a href="#">Privacy</a></li>
                            </ul>
                            <ul class="list-unstyled float-start links">
                                <li><a href="#">Partners</a></li>
                                <li><a href="#">Business</a></li>
                                <li><a href="#">Careers</a></li>
                                <li><a href="#">Blog</a></li>
                                <li><a href="#">FAQ</a></li>
                                <li><a href="#">Creative</a></li>
                            </ul>
                        </div> <!-- /.widget -->
                    </div> <!-- /.col-lg-4 -->
                    <div class="col-lg-4">
                        <div class="widget">
                            <h2 class="mb-4 text-center" style="font-family: 'Playfair Display', serif;">I am Uche</h2>
                            <div class="post-entry-footer">
                                <div class="container">
                                    <div class="row">
                                      <div class="col-md-6">
                                        <img src="https://uchennaoji.wordpress.com/wp-content/uploads/2024/06/uche.jpg?w=320" alt="Profile Picture" class="img-fluid" style="border-radius: 50%; width: 200px; height: 200px; object-fit: cover;">
                                      </div>
                                      <div class="col-md-6">
                                        Welcome to my cozy corner of the internet dedicated to all things bold and beautiful. Here, I invite you to join me on a journey of becoming more emotionally mature, happy and confident as you grow into the best version of you. Let’s get going!</p>
                                      </div>
                                    </div>
                                </div>
                            </div>    
                                                
</body>

templates/category.html
<!-- /*
* Template Name: Blogy
* Template Author: Untree.co
* Template URI: https://untree.co/
* License: https://creativecommons.org/licenses/by/3.0/
*/ -->
{% load static %}
<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="author" content="Untree.co">
	<link rel="shortcut icon" href="{% static 'favicon.png' %}">

	<meta name="description" content="" />
	<meta name="keywords" content="bootstrap, bootstrap5" />

	<link rel="preconnect" href="{% static 'https://fonts.googleapis.com' %}">
	<link rel="preconnect" href="{% static 'https://fonts.gstatic.com' %}" crossorigin>
	<link href="{% static 'https://fonts.googleapis.com/css2?family=Work+Sans:wght@400;600;700&display=swap' %}" rel="stylesheet">


	<link rel="stylesheet" href="{% static 'fonts/icomoon/style.css' %}">
	<link rel="stylesheet" href="{% static 'fonts/flaticon/font/flaticon.css' %}">

	<link rel="stylesheet" href="{% static 'https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css' %}">

	<link rel="stylesheet" href="{% static 'css/tiny-slider.css' %}">
	<link rel="stylesheet" href="{% static 'css/aos.css' %}">
	<link rel="stylesheet" href="{% static 'css/glightbox.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/style.css' %}">

	<link rel="stylesheet" href="{% static 'css/flatpickr.min.css' %}">


	<title>Blogy &mdash; Free Bootstrap 5 Website Template by Untree.co</title>
</head>
<body>

	<div class="site-mobile-menu site-navbar-target">
		<div class="site-mobile-menu-header">
			<div class="site-mobile-menu-close">
				<span class="icofont-close js-menu-toggle"></span>
			</div>
		</div>
		<div class="site-mobile-menu-body"></div>
	</div>

	<nav class="site-nav">
		<div class="container">
			<div class="menu-bg-wrap">
				<div class="site-navigation">
					<div class="row g-0 align-items-center">
						<div class="col-2">
							<a href="{% static 'index.html' %}" class="logo m-0 float-start">Blogy<span class="text-primary">.</span></a>
						</div>
						<div class="col-8 text-center">
							<form action="#" class="search-form d-inline-block d-lg-none">
								<input type="text" class="form-control" placeholder="Search...">
								<span class="bi-search"></span>
							</form>

							<ul class="js-clone-nav d-none d-lg-inline-block text-start site-menu mx-auto">
								<li><a href="{% url 'index' %}">Home</a></li>
								<li class="has-children active">
									<a href="{% static 'financing.html' %}">Pages</a>
									<ul class="dropdown">
										<li><a href="{% static 'search-result.html' %}">Search Result</a></li>
										<li><a href="{% static 'blog.html' %}">Blog</a></li>
										<li><a href="{% static 'single.html' %}">Blog Single</a></li>
										<li class="active"><a href="{% static 'category.html' %}">Category</a></li>
										<li><a href="{% static 'about.html' %}">About</a></li>
										<li><a href="{% static 'contact.html' %}">Contact Us</a></li>
										<li><a href="#">Menu One</a></li>
										<li><a href="#">Menu Two</a></li>
										<li class="has-children">
											<a href="#">Categories</a>
											<ul class="dropdown">
												{% for cats in all_cats %}
												<li><a href="{% url 'category' cats %}">{{cats}}</a></li>
												{%endfor%}
											</ul>
										</li>
									</ul>
								</li>
								{% for cats in all_cats %}
								    <li><a href="{% url 'category' cats %}">{{cats}}</a></li>
								<!-- <li><a href="{% static 'category.html' %}">Culture</a></li>
								<li><a href="{% static 'services.html' %}">Business</a></li>
								<li><a href="{% static 'about.html' %}">Politics</a></li> -->
								{%endfor%}
							</ul>
						</div>
						<div class="col-2 text-end">
							<a href="#" class="burger ms-auto float-end site-menu-toggle js-menu-toggle d-inline-block d-lg-none light">
								<span></span>
							</a>
							<form action="#" class="search-form d-none d-lg-inline-block">
								<input type="text" class="form-control" placeholder="Search...">
								<span class="bi-search"></span>
							</form>
						</div>
					</div>
				</div>
			</div>
		</div>
	</nav>

	<div class="section search-result-wrap">
		<div class="container">
			<div class="row">
				<div class="col-12">
					<div class="heading">Category: {{cats}}</div>
				</div>
			</div>
			<div class="row posts-entry">
				<div class="col-lg-8">
					<h3>check our latest</h3>
					{% for post in cat_post%}
					<div class="blog-entry d-flex blog-entry-search-item">
						<a href="{% static 'single.html' %}" class="img-link me-4">
							<img src=" {% static 'images/img_1_sq.jpg' %}" alt="Image" class="img-fluid">
						</a>
						<div>
							<h3>{{post.category}} </h3>
							<span>{{post.created_at}} &bullet; <a href="#">Categories</a></span>
							<h2><a href="{% static 'single.html' %}">{{post.title}}</a></h2>
							<p>{{post.body|truncatewords:10}}</p>
							<p><a href="{% static 'single.html' %}" class="btn btn-sm btn-outline-primary">Read More</a></p>
						</div>
						
					</div>

					{% endfor %}
					<div class="row text-start pt-5 border-top">
						<div class="col-md-12">
							<div class="custom-pagination">
								<span>1</span>
								<a href="#">2</a>
								<a href="#">3</a>
								<a href="#">4</a>
								<span>...</span>
								<a href="#">15</a>
							</div>
						</div>
					</div>


				</div>

				<div class="col-lg-4 sidebar">
					
					<div class="sidebar-box search-form-wrap mb-4">
						<form action="#" class="sidebar-search-form">
							<span class="bi-search"></span>
							<input type="text" class="form-control" id="s" placeholder="Type a keyword and hit enter">
						</form>
					</div>
					<!-- END sidebar-box -->
					<div class="sidebar-box">
						<h3 class="heading">Popular Posts</h3>
						<div class="post-entry-sidebar">
							<ul>
								<li>
									<a ">
										<img src=" {% static 'images/img_1_sq.jpg' %}" alt="Image placeholder" class="me-4 rounded">
										<div class="text">
											<h4>There’s a Cool New Way for Men to Wear Socks and Sandals</h4>
											<div class="post-meta">
												<span class="mr-2">March 15, 2018 </span>
											</div>
										</div>
									</a>
								</li>
								<li>
									<a ">
										<img src=" {% static 'images/img_2_sq.jpg' %}" alt="Image placeholder" class="me-4 rounded">
										<div class="text">
											<h4>There’s a Cool New Way for Men to Wear Socks and Sandals</h4>
											<div class="post-meta">
												<span class="mr-2">March 15, 2018 </span>
											</div>
										</div>
									</a>
								</li>
								<li>
									<a ">
										<img src=" {% static 'images/img_3_sq.jpg' %}" alt="Image placeholder" class="me-4 rounded">
										<div class="text">
											<h4>There’s a Cool New Way for Men to Wear Socks and Sandals</h4>
											<div class="post-meta">
												<span class="mr-2">March 15, 2018 </span>
											</div>
										</div>
									</a>
								</li>
							</ul>
						</div>
					</div>
					<!-- END sidebar-box -->

					<div class="sidebar-box">
						<h3 class="heading">Categories</h3>
						<ul class="categories">
							{% for category in all_cats %}
								<li><a href="#">{{category.catName}} <span> {{category.post_count}} </span></a></li>
							{% empty %}
								<h2>No category</h2>
							{% endfor %}
						</ul>
					</div>
					<!-- END sidebar-box -->

					<div class="sidebar-box">
						<h3 class="heading">Tags</h3>
						<ul class="tags">
							<li><a href="#">Travel</a></li>
							<li><a href="#">Adventure</a></li>
							<li><a href="#">Food</a></li>
							<li><a href="#">Lifestyle</a></li>
							<li><a href="#">Business</a></li>
							<li><a href="#">Freelancing</a></li>
							<li><a href="#">Travel</a></li>
							<li><a href="#">Adventure</a></li>
							<li><a href="#">Food</a></li>
							<li><a href="#">Lifestyle</a></li>
							<li><a href="#">Business</a></li>
							<li><a href="#">Freelancing</a></li>
						</ul>
					</div>

				</div>
			</div>
		</div>
	</div>

	<footer class="site-footer">
		<div class="container">
			<div class="row">
				<div class="col-lg-4">
					<div class="widget">
						<h3 class="mb-4">About</h3>
						<p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
					</div> <!-- /.widget -->
					<div class="widget">
						<h3>Social</h3>
						<ul class="list-unstyled social">
							<li><a href="#"><span class="icon-instagram"></span></a></li>
							<li><a href="#"><span class="icon-twitter"></span></a></li>
							<li><a href="#"><span class="icon-facebook"></span></a></li>
							<li><a href="#"><span class="icon-linkedin"></span></a></li>
							<li><a href="#"><span class="icon-pinterest"></span></a></li>
							<li><a href="#"><span class="icon-dribbble"></span></a></li>
						</ul>
					</div> <!-- /.widget -->
				</div> <!-- /.col-lg-4 -->
				<div class="col-lg-4 ps-lg-5">
					<div class="widget">
						<h3 class="mb-4">Company</h3>
						<ul class="list-unstyled float-start links">
							<li><a href="#">About us</a></li>
							<li><a href="#">Services</a></li>
							<li><a href="#">Vision</a></li>
							<li><a href="#">Mission</a></li>
							<li><a href="#">Terms</a></li>
							<li><a href="#">Privacy</a></li>
						</ul>
						<ul class="list-unstyled float-start links">
							<li><a href="#">Partners</a></li>
							<li><a href="#">Business</a></li>
							<li><a href="#">Careers</a></li>
							<li><a href="#">Blog</a></li>
							<li><a href="#">FAQ</a></li>
							<li><a href="#">Creative</a></li>
						</ul>
					</div> <!-- /.widget -->
				</div> <!-- /.col-lg-4 -->
				<div class="col-lg-4">
					<div class="widget">
						<h3 class="mb-4">Recent Post Entry</h3>
						<div class="post-entry-footer">
							<ul>
								<li>
									<a ">
										<img src=" {% static 'images/img_1_sq.jpg' %}" alt="Image placeholder" class="me-4 rounded">
										<div class="text">
											<h4>There’s a Cool New Way for Men to Wear Socks and Sandals</h4>
											<div class="post-meta">
												<span class="mr-2">March 15, 2018 </span>
											</div>
										</div>
									</a>
								</li>
								<li>
									<a ">
										<img src=" {% static 'images/img_2_sq.jpg' %}" alt="Image placeholder" class="me-4 rounded">
										<div class="text">
											<h4>There’s a Cool New Way for Men to Wear Socks and Sandals</h4>
											<div class="post-meta">
												<span class="mr-2">March 15, 2018 </span>
											</div>
										</div>
									</a>
								</li>
								<li>
									<a ">
										<img src=" {% static 'images/img_3_sq.jpg' %}" alt="Image placeholder" class="me-4 rounded">
										<div class="text">
											<h4>There’s a Cool New Way for Men to Wear Socks and Sandals</h4>
											<div class="post-meta">
												<span class="mr-2">March 15, 2018 </span>
											</div>
										</div>
									</a>
								</li>
							</ul>
						</div>


					</div> <!-- /.widget -->
				</div> <!-- /.col-lg-4 -->
			</div> <!-- /.row -->

			<div class="row mt-5">
				<div class="col-12 text-center">
          <!-- 
              **==========
              NOTE: 
              Please don't remove this copyright link unless you buy the license here https://untree.co/license/  
              **==========
            -->

            <p>Copyright &copy;<script>document.write(new Date().getFullYear());</script>. All Rights Reserved. &mdash; Designed with love by <a href="{% static 'https://untree.co">Untree.co</a> Distributed by <a href="{% static 'https://themewagon.com">ThemeWagon</a>  <!-- License information: https://untree.co/license/ -->
            </p>
          </div>
        </div>
      </div> <!-- /.container -->
    </footer> <!-- /.site-footer -->

    <!-- Preloader -->
    <div id="overlayer"></div>
    <div class="loader">
    	<div class="spinner-border text-primary" role="status">
    		<span class="visually-hidden">Loading...</span>
    	</div>
    </div>


    <script src=" {% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src=" {% static 'js/tiny-slider.js' %}"></script>

    <script src=" {% static 'js/flatpickr.min.js' %}"></script>


    <script src=" {% static 'js/aos.js' %}"></script>
    <script src=" {% static 'js/glightbox.min.js' %}"></script>
    <script src=" {% static 'js/navbar.js' %}"></script>
    <script src=" {% static 'js/counter.js' %}"></script>
    <script src=" {% static 'js/custom.js' %}"></script>

    
  </body>
  </html>

templates/comment.html
{% load static %}

{% if user.is_authenticated %}
<div class="pt-2 comment-form-wrap">
    <small><h5 class="mb-2"> Leave a Comment </h5></small> 
      <form method="post" class="p-5 bg-light" action="{% url 'comment-sent' post.id %}">
          {% csrf_token %}
          {{ commentForm }}
          <button type="submit"class="btn btn-primary sm">Post comment</button>
      </form>
      <br>
    <small >{{post.comments.count}} Comments</small>
    <hr>
    <ul class="comment-list">
      {% for comment in post.comments.all %}
        <li class="comment">
            <div class="vcard">
                <img src=" {% static 'images/person_1.jpg' %}" alt="Image placeholder">
            </div>
            <div class="comment-body">
                <h3>{{ comment.author }}</h3>
                <div class="meta"> {{date_added}} </div>
                <p> {{ comment.author }}: {{comment.body}} <p>
                <a href="#" class="reply-btn" data-id="{{ comment.id }}">Reply</a> | 
                {%if user.is_authenticated and comment.author ==  user %}
                    <a href="{% url 'comment-delete' comment.id %}" class="delete">Delete</a>
                {% endif %}  
                <form method="POST" action="{% url 'add-reply' comment.id %}" class="reply-form" id="reply-form-{{ comment.id }}" style="display: none;">
                    {% csrf_token %}
                    {{ replyForm }}
                <button type="submit" class="btn reply">Post Reply</button>
                </form>
            </p><p>Debug Comment ID: {{ comment.id }}</p>
            
            {% for reply in post.comment.replies.all %}
            <div class="reply" id="reply-{{ reply.id }}">
                <p>{{ reply.author }}</p>
                <p>{{ reply.body }}</p> 
                {%if user.is_authenticated and comment.author ==  user %}
                    <a href="#" class="delete-btn" data-id="{{ reply.id }}">Delete</a>
                {% endif %} 
                <form method="POST" action="#" class="delete-form" id="delete-form-{{ reply.id }}" style="display: none;">
                    {% csrf_token %}
                <button class="delete-reply-btn" data-id="{{ reply.id }}">Delete</button>
                </form>
            </div>
            <p>Debug Reply ID: {{ reply.id }}</p>

            {% endfor %}
          </div>
          
        </li>
      {% empty %}
        <p>Be the first to Comment.</p>
      {%endfor%}
    </ul>
  </div>
  {% else %}
  <a href="{% url 'login' %}"><small>Login to Make a Comment</small></a>
  {% endif %}


<script>

    document.addEventListener("DOMContentLoaded", function() {
        const replyButtons = document.querySelectorAll('.reply-btn'); // Select all "Reply" links
        replyButtons.forEach(button => {
            button.addEventListener('click', function(e) {
                e.preventDefault(); // Prevent the default action of the link (navigating to "#")
                const formId = `reply-form-${this.dataset.id}`; // Get the ID of the form
                const form = document.getElementById(formId); // Locate the form element
                if (form.style.display === "none") {
                    form.style.display = "block"; // Show the form
                } else {
                    form.style.display = "none"; // Hide the form
                }
            });
        });
});
console.log(`Form ID: ${formId}`);
console.log(form); // Check if the form is found

    document.addEventListener("DOMContentLoaded", function () {
    const deleteButtons = document.querySelectorAll(".delete-reply-btn");

    deleteButtons.forEach((button) => {
        button.addEventListener("click", function (e) {
            e.preventDefault();

            const replyId = this.dataset.id; // Get the reply ID from the button
            const replyElement = document.getElementById(`reply-${replyId}`); // Target the reply div

            // Send the AJAX request
            fetch(`/reply_delete/${replyId}/`, {
                method: "POST",
                headers: {
                    "X-CSRFToken": document.querySelector("[name=csrfmiddlewaretoken]").value,
                    "Content-Type": "application/json",
                },
            })
                .then((response) => response.json())
                .then((data) => {
                    if (data.success) {
                        // Remove the reply from the DOM
                        replyElement.remove();
                        alert(data.message);
                    } else {
                        alert(data.message);
                    }
                })
                .catch((error) => {
                    console.error("Error:", error);
                    alert("An error occurred while deleting the reply.");
                });
        });
    });
});

</script>
  

  

templates/comment_delete.html
<h1>Delete Comment</h1>

<comment class="card p-4 !mb-4">
    <div class="flex justify-between items-center"> 
        <a class="flex items-center gap-1 mb-2" href="">
            <img class="w-8 h-8 object-cover rounded-full" src="https://pbs.twimg.com/profile_images/508601156767997952/fFTdKUf2_400x400.jpeg"> 
            <span class="font-bold hover:underline">Bart</span><span class="text-sm font-normal text-gray-400">@bartsimpson</span>
        </a>
    </div>
    <p class="text-xl px-2">
        This is a comment from Bart
    </p>
    <div x-data="{ repliesOpen: false }" class="flex items-center justify-between flex-wrap text-sm px-2">
        <a @click=" repliesOpen = !repliesOpen" class="font-bold hover:underline cursor-pointer">
            <div class="inline-block" x-bind:class="repliesOpen && 'rotate-90 duration-300'">
                <svg transform ="rotate(90)" width="9" height="9" viewBox="0 0 25 25">
                    <path d="M24 22h-24l12-20z"/>
                </svg>
            </div>
            Replies
            <span class="font-light text-gray-500 ml-1">1</span>
        </a>
        <div class="flex items-center gap-4 [&>a:hover]:underline">
            <div class="flex items-center gap-1">
                <img class="w-5 -mt-1" src="https://img.icons8.com/small/24/000000/fire-heart.png">1</div>
            <a href="">Like</a>
            <a href="">Delete</a>
        </div>
    </div> 
</comment>

<p class="my-6">Are you sure you want to delete this comment?</p>

<form method='POST'>
    {%csrf_token%}
    <button type="submit">Confirm</button>
    <a class="button secondaryAction ml-1" href="{{requst.META.HTTP_REFERER}}">Go Back</a>
</form>

templates/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Delete Post</title>
</head>
<body>
    {% if user.is_authenticated %}
    <h2>Delete: {{post.title}} </h2>
    <div class="form-group">
        <form method="POST">
            {% csrf_token %}
            <small>Are you sure you want to delete this post</small><br><br>
            <button class=" =btn btn-secondary">Delete</button>
        </form>
    </div> 
    {% else %}
    <h1>You are not allowed to perform this action</h1>
    {%endif%}
</body>
</html>